/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as MachinesRouteImport } from './routes/machines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as CiRouteImport } from './routes/ci'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiUsersUpdateStatusRouteImport } from './routes/api/users/update-status'
import { Route as ApiUsersSetAdminRouteImport } from './routes/api/users/set-admin'
import { Route as ApiUsersListRouteImport } from './routes/api/users/list'
import { Route as ApiQueuesStatusRouteImport } from './routes/api/queues/status'
import { Route as ApiQueuesJobsRouteImport } from './routes/api/queues/jobs'
import { Route as ApiQueuesControlRouteImport } from './routes/api/queues/control'
import { Route as ApiMachinesUpdateRouteImport } from './routes/api/machines/update'
import { Route as ApiMachinesListRouteImport } from './routes/api/machines/list'
import { Route as ApiMachinesExclusiveUsersRouteImport } from './routes/api/machines/exclusive-users'
import { Route as ApiMachinesDeleteRouteImport } from './routes/api/machines/delete'
import { Route as ApiCalendarMachinesRouteImport } from './routes/api/calendar/machines'
import { Route as ApiCalendarEventsRouteImport } from './routes/api/calendar/events'
import { Route as ApiCalendarAvailabilityRouteImport } from './routes/api/calendar/availability'
import { Route as ApiBookingsListRouteImport } from './routes/api/bookings/list'
import { Route as ApiBookingsDeleteRouteImport } from './routes/api/bookings/delete'
import { Route as ApiBookingsCreateRouteImport } from './routes/api/bookings/create'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAnsibleHealthCheckRouteImport } from './routes/api/ansible/health-check'
import { Route as ApiAnsibleExecuteRouteImport } from './routes/api/ansible/execute'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesRoute = MachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CiRoute = CiRouteImport.update({
  id: '/ci',
  path: '/ci',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUpdateStatusRoute = ApiUsersUpdateStatusRouteImport.update({
  id: '/api/users/update-status',
  path: '/api/users/update-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersSetAdminRoute = ApiUsersSetAdminRouteImport.update({
  id: '/api/users/set-admin',
  path: '/api/users/set-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersListRoute = ApiUsersListRouteImport.update({
  id: '/api/users/list',
  path: '/api/users/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueuesStatusRoute = ApiQueuesStatusRouteImport.update({
  id: '/api/queues/status',
  path: '/api/queues/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueuesJobsRoute = ApiQueuesJobsRouteImport.update({
  id: '/api/queues/jobs',
  path: '/api/queues/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueuesControlRoute = ApiQueuesControlRouteImport.update({
  id: '/api/queues/control',
  path: '/api/queues/control',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMachinesUpdateRoute = ApiMachinesUpdateRouteImport.update({
  id: '/api/machines/update',
  path: '/api/machines/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMachinesListRoute = ApiMachinesListRouteImport.update({
  id: '/api/machines/list',
  path: '/api/machines/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMachinesExclusiveUsersRoute =
  ApiMachinesExclusiveUsersRouteImport.update({
    id: '/api/machines/exclusive-users',
    path: '/api/machines/exclusive-users',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMachinesDeleteRoute = ApiMachinesDeleteRouteImport.update({
  id: '/api/machines/delete',
  path: '/api/machines/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarMachinesRoute = ApiCalendarMachinesRouteImport.update({
  id: '/api/calendar/machines',
  path: '/api/calendar/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarEventsRoute = ApiCalendarEventsRouteImport.update({
  id: '/api/calendar/events',
  path: '/api/calendar/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarAvailabilityRoute = ApiCalendarAvailabilityRouteImport.update({
  id: '/api/calendar/availability',
  path: '/api/calendar/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsListRoute = ApiBookingsListRouteImport.update({
  id: '/api/bookings/list',
  path: '/api/bookings/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsDeleteRoute = ApiBookingsDeleteRouteImport.update({
  id: '/api/bookings/delete',
  path: '/api/bookings/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsCreateRoute = ApiBookingsCreateRouteImport.update({
  id: '/api/bookings/create',
  path: '/api/bookings/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnsibleHealthCheckRoute = ApiAnsibleHealthCheckRouteImport.update({
  id: '/api/ansible/health-check',
  path: '/api/ansible/health-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnsibleExecuteRoute = ApiAnsibleExecuteRouteImport.update({
  id: '/api/ansible/execute',
  path: '/api/ansible/execute',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/ci': typeof CiRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/machines': typeof MachinesRoute
  '/users': typeof UsersRoute
  '/api/ansible/execute': typeof ApiAnsibleExecuteRoute
  '/api/ansible/health-check': typeof ApiAnsibleHealthCheckRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/bookings/create': typeof ApiBookingsCreateRoute
  '/api/bookings/delete': typeof ApiBookingsDeleteRoute
  '/api/bookings/list': typeof ApiBookingsListRoute
  '/api/calendar/availability': typeof ApiCalendarAvailabilityRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/calendar/machines': typeof ApiCalendarMachinesRoute
  '/api/machines/delete': typeof ApiMachinesDeleteRoute
  '/api/machines/exclusive-users': typeof ApiMachinesExclusiveUsersRoute
  '/api/machines/list': typeof ApiMachinesListRoute
  '/api/machines/update': typeof ApiMachinesUpdateRoute
  '/api/queues/control': typeof ApiQueuesControlRoute
  '/api/queues/jobs': typeof ApiQueuesJobsRoute
  '/api/queues/status': typeof ApiQueuesStatusRoute
  '/api/users/list': typeof ApiUsersListRoute
  '/api/users/set-admin': typeof ApiUsersSetAdminRoute
  '/api/users/update-status': typeof ApiUsersUpdateStatusRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/ci': typeof CiRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/machines': typeof MachinesRoute
  '/users': typeof UsersRoute
  '/api/ansible/execute': typeof ApiAnsibleExecuteRoute
  '/api/ansible/health-check': typeof ApiAnsibleHealthCheckRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/bookings/create': typeof ApiBookingsCreateRoute
  '/api/bookings/delete': typeof ApiBookingsDeleteRoute
  '/api/bookings/list': typeof ApiBookingsListRoute
  '/api/calendar/availability': typeof ApiCalendarAvailabilityRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/calendar/machines': typeof ApiCalendarMachinesRoute
  '/api/machines/delete': typeof ApiMachinesDeleteRoute
  '/api/machines/exclusive-users': typeof ApiMachinesExclusiveUsersRoute
  '/api/machines/list': typeof ApiMachinesListRoute
  '/api/machines/update': typeof ApiMachinesUpdateRoute
  '/api/queues/control': typeof ApiQueuesControlRoute
  '/api/queues/jobs': typeof ApiQueuesJobsRoute
  '/api/queues/status': typeof ApiQueuesStatusRoute
  '/api/users/list': typeof ApiUsersListRoute
  '/api/users/set-admin': typeof ApiUsersSetAdminRoute
  '/api/users/update-status': typeof ApiUsersUpdateStatusRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/ci': typeof CiRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/machines': typeof MachinesRoute
  '/users': typeof UsersRoute
  '/api/ansible/execute': typeof ApiAnsibleExecuteRoute
  '/api/ansible/health-check': typeof ApiAnsibleHealthCheckRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/bookings/create': typeof ApiBookingsCreateRoute
  '/api/bookings/delete': typeof ApiBookingsDeleteRoute
  '/api/bookings/list': typeof ApiBookingsListRoute
  '/api/calendar/availability': typeof ApiCalendarAvailabilityRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/calendar/machines': typeof ApiCalendarMachinesRoute
  '/api/machines/delete': typeof ApiMachinesDeleteRoute
  '/api/machines/exclusive-users': typeof ApiMachinesExclusiveUsersRoute
  '/api/machines/list': typeof ApiMachinesListRoute
  '/api/machines/update': typeof ApiMachinesUpdateRoute
  '/api/queues/control': typeof ApiQueuesControlRoute
  '/api/queues/jobs': typeof ApiQueuesJobsRoute
  '/api/queues/status': typeof ApiQueuesStatusRoute
  '/api/users/list': typeof ApiUsersListRoute
  '/api/users/set-admin': typeof ApiUsersSetAdminRoute
  '/api/users/update-status': typeof ApiUsersUpdateStatusRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/ci'
    | '/help'
    | '/login'
    | '/machines'
    | '/users'
    | '/api/ansible/execute'
    | '/api/ansible/health-check'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/bookings/create'
    | '/api/bookings/delete'
    | '/api/bookings/list'
    | '/api/calendar/availability'
    | '/api/calendar/events'
    | '/api/calendar/machines'
    | '/api/machines/delete'
    | '/api/machines/exclusive-users'
    | '/api/machines/list'
    | '/api/machines/update'
    | '/api/queues/control'
    | '/api/queues/jobs'
    | '/api/queues/status'
    | '/api/users/list'
    | '/api/users/set-admin'
    | '/api/users/update-status'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/ci'
    | '/help'
    | '/login'
    | '/machines'
    | '/users'
    | '/api/ansible/execute'
    | '/api/ansible/health-check'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/bookings/create'
    | '/api/bookings/delete'
    | '/api/bookings/list'
    | '/api/calendar/availability'
    | '/api/calendar/events'
    | '/api/calendar/machines'
    | '/api/machines/delete'
    | '/api/machines/exclusive-users'
    | '/api/machines/list'
    | '/api/machines/update'
    | '/api/queues/control'
    | '/api/queues/jobs'
    | '/api/queues/status'
    | '/api/users/list'
    | '/api/users/set-admin'
    | '/api/users/update-status'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/ci'
    | '/help'
    | '/login'
    | '/machines'
    | '/users'
    | '/api/ansible/execute'
    | '/api/ansible/health-check'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/bookings/create'
    | '/api/bookings/delete'
    | '/api/bookings/list'
    | '/api/calendar/availability'
    | '/api/calendar/events'
    | '/api/calendar/machines'
    | '/api/machines/delete'
    | '/api/machines/exclusive-users'
    | '/api/machines/list'
    | '/api/machines/update'
    | '/api/queues/control'
    | '/api/queues/jobs'
    | '/api/queues/status'
    | '/api/users/list'
    | '/api/users/set-admin'
    | '/api/users/update-status'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  CiRoute: typeof CiRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MachinesRoute: typeof MachinesRoute
  UsersRoute: typeof UsersRoute
  ApiAnsibleExecuteRoute: typeof ApiAnsibleExecuteRoute
  ApiAnsibleHealthCheckRoute: typeof ApiAnsibleHealthCheckRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiBookingsCreateRoute: typeof ApiBookingsCreateRoute
  ApiBookingsDeleteRoute: typeof ApiBookingsDeleteRoute
  ApiBookingsListRoute: typeof ApiBookingsListRoute
  ApiCalendarAvailabilityRoute: typeof ApiCalendarAvailabilityRoute
  ApiCalendarEventsRoute: typeof ApiCalendarEventsRoute
  ApiCalendarMachinesRoute: typeof ApiCalendarMachinesRoute
  ApiMachinesDeleteRoute: typeof ApiMachinesDeleteRoute
  ApiMachinesExclusiveUsersRoute: typeof ApiMachinesExclusiveUsersRoute
  ApiMachinesListRoute: typeof ApiMachinesListRoute
  ApiMachinesUpdateRoute: typeof ApiMachinesUpdateRoute
  ApiQueuesControlRoute: typeof ApiQueuesControlRoute
  ApiQueuesJobsRoute: typeof ApiQueuesJobsRoute
  ApiQueuesStatusRoute: typeof ApiQueuesStatusRoute
  ApiUsersListRoute: typeof ApiUsersListRoute
  ApiUsersSetAdminRoute: typeof ApiUsersSetAdminRoute
  ApiUsersUpdateStatusRoute: typeof ApiUsersUpdateStatusRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines': {
      id: '/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ci': {
      id: '/ci'
      path: '/ci'
      fullPath: '/ci'
      preLoaderRoute: typeof CiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/update-status': {
      id: '/api/users/update-status'
      path: '/api/users/update-status'
      fullPath: '/api/users/update-status'
      preLoaderRoute: typeof ApiUsersUpdateStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/set-admin': {
      id: '/api/users/set-admin'
      path: '/api/users/set-admin'
      fullPath: '/api/users/set-admin'
      preLoaderRoute: typeof ApiUsersSetAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/list': {
      id: '/api/users/list'
      path: '/api/users/list'
      fullPath: '/api/users/list'
      preLoaderRoute: typeof ApiUsersListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queues/status': {
      id: '/api/queues/status'
      path: '/api/queues/status'
      fullPath: '/api/queues/status'
      preLoaderRoute: typeof ApiQueuesStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queues/jobs': {
      id: '/api/queues/jobs'
      path: '/api/queues/jobs'
      fullPath: '/api/queues/jobs'
      preLoaderRoute: typeof ApiQueuesJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queues/control': {
      id: '/api/queues/control'
      path: '/api/queues/control'
      fullPath: '/api/queues/control'
      preLoaderRoute: typeof ApiQueuesControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/machines/update': {
      id: '/api/machines/update'
      path: '/api/machines/update'
      fullPath: '/api/machines/update'
      preLoaderRoute: typeof ApiMachinesUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/machines/list': {
      id: '/api/machines/list'
      path: '/api/machines/list'
      fullPath: '/api/machines/list'
      preLoaderRoute: typeof ApiMachinesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/machines/exclusive-users': {
      id: '/api/machines/exclusive-users'
      path: '/api/machines/exclusive-users'
      fullPath: '/api/machines/exclusive-users'
      preLoaderRoute: typeof ApiMachinesExclusiveUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/machines/delete': {
      id: '/api/machines/delete'
      path: '/api/machines/delete'
      fullPath: '/api/machines/delete'
      preLoaderRoute: typeof ApiMachinesDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/machines': {
      id: '/api/calendar/machines'
      path: '/api/calendar/machines'
      fullPath: '/api/calendar/machines'
      preLoaderRoute: typeof ApiCalendarMachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/events': {
      id: '/api/calendar/events'
      path: '/api/calendar/events'
      fullPath: '/api/calendar/events'
      preLoaderRoute: typeof ApiCalendarEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/availability': {
      id: '/api/calendar/availability'
      path: '/api/calendar/availability'
      fullPath: '/api/calendar/availability'
      preLoaderRoute: typeof ApiCalendarAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings/list': {
      id: '/api/bookings/list'
      path: '/api/bookings/list'
      fullPath: '/api/bookings/list'
      preLoaderRoute: typeof ApiBookingsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings/delete': {
      id: '/api/bookings/delete'
      path: '/api/bookings/delete'
      fullPath: '/api/bookings/delete'
      preLoaderRoute: typeof ApiBookingsDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings/create': {
      id: '/api/bookings/create'
      path: '/api/bookings/create'
      fullPath: '/api/bookings/create'
      preLoaderRoute: typeof ApiBookingsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ansible/health-check': {
      id: '/api/ansible/health-check'
      path: '/api/ansible/health-check'
      fullPath: '/api/ansible/health-check'
      preLoaderRoute: typeof ApiAnsibleHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ansible/execute': {
      id: '/api/ansible/execute'
      path: '/api/ansible/execute'
      fullPath: '/api/ansible/execute'
      preLoaderRoute: typeof ApiAnsibleExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  CiRoute: CiRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MachinesRoute: MachinesRoute,
  UsersRoute: UsersRoute,
  ApiAnsibleExecuteRoute: ApiAnsibleExecuteRoute,
  ApiAnsibleHealthCheckRoute: ApiAnsibleHealthCheckRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiBookingsCreateRoute: ApiBookingsCreateRoute,
  ApiBookingsDeleteRoute: ApiBookingsDeleteRoute,
  ApiBookingsListRoute: ApiBookingsListRoute,
  ApiCalendarAvailabilityRoute: ApiCalendarAvailabilityRoute,
  ApiCalendarEventsRoute: ApiCalendarEventsRoute,
  ApiCalendarMachinesRoute: ApiCalendarMachinesRoute,
  ApiMachinesDeleteRoute: ApiMachinesDeleteRoute,
  ApiMachinesExclusiveUsersRoute: ApiMachinesExclusiveUsersRoute,
  ApiMachinesListRoute: ApiMachinesListRoute,
  ApiMachinesUpdateRoute: ApiMachinesUpdateRoute,
  ApiQueuesControlRoute: ApiQueuesControlRoute,
  ApiQueuesJobsRoute: ApiQueuesJobsRoute,
  ApiQueuesStatusRoute: ApiQueuesStatusRoute,
  ApiUsersListRoute: ApiUsersListRoute,
  ApiUsersSetAdminRoute: ApiUsersSetAdminRoute,
  ApiUsersUpdateStatusRoute: ApiUsersUpdateStatusRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
